/**
 * Fee accrual model — estimates fees earned per time step when in-range.
 *
 * Model: fees_per_step = (position_share) * (volume_per_step) * (fee_rate)
 * where position_share = position_liquidity / total_pool_liquidity
 *
 * Since we don't have real-time volume data, we assume constant daily volume
 * and distribute it evenly across time steps.
 */

import type { BacktestConfig } from './types.js';
import { bigintToFloat, tickToPrice } from './alm_bridge.js';

/**
 * Calculate fees earned for one time step (typically 60 seconds).
 *
 * Returns fees in USD (floating point) since we're working with
 * assumed pool volume in USD terms.
 *
 * @param positionLiquidity - Position's liquidity (BigInt)
 * @param poolLiquidityUsd - Total pool liquidity in USD
 * @param dailyVolumeUsd - Daily trading volume in USD
 * @param feeRateBps - Fee rate in basis points (e.g., 2500 for 0.25%)
 * @param stepSeconds - Duration of one time step in seconds
 * @param isInRange - Whether position is currently in range
 */
export function calculateStepFees(
  positionLiquidity: bigint,
  poolLiquidityUsd: number,
  dailyVolumeUsd: number,
  feeRateBps: number,
  stepSeconds: number,
  isInRange: boolean,
): number {
  if (!isInRange || positionLiquidity === 0n || poolLiquidityUsd <= 0) {
    return 0;
  }

  // Fee rate as decimal (e.g., 2500 bps = 0.0025)
  const feeRate = feeRateBps / 1_000_000;

  // Volume per step
  const volumePerStep = (dailyVolumeUsd * stepSeconds) / 86400;

  // Fees generated by pool per step
  const poolFeesPerStep = volumePerStep * feeRate;

  // We model the position as capturing a share of pool fees.
  // In reality this depends on liquidity concentration, but for a
  // simplified model we use: our_share = our_capital / total_pool_tvl
  // This is a reasonable approximation for positions of moderate size.
  //
  // For a more accurate model (Phase 3), we'd compute the exact
  // liquidity ratio using the position's tick range vs pool's tick range.
  //
  // For now: position_share = initial_capital / pool_liquidity
  // This is set once and stays constant through the simulation.
  // The actual share value is computed in the simulator and passed here.

  return poolFeesPerStep;
}

/**
 * Estimate the position's share of pool fees based on capital deployed.
 * This is a simplified model: share = capital_usd / pool_tvl_usd.
 *
 * A more accurate V3 model would use:
 *   share = position_liquidity / active_pool_liquidity
 * which depends on the tick range width and current price.
 * We'll add that refinement in Phase 3.
 */
export function estimatePositionShare(
  capitalUsd: number,
  poolLiquidityUsd: number,
): number {
  if (poolLiquidityUsd <= 0) return 0;
  return capitalUsd / poolLiquidityUsd;
}

/**
 * Convert a USD fee amount to token0-equivalent BigInt for position tracking.
 */
export function feeUsdToToken0(
  feeUsd: number,
  priceToken0Usd: number,
  decimals0: number,
): bigint {
  if (priceToken0Usd <= 0) return 0n;
  const amountFloat = feeUsd / priceToken0Usd;
  return BigInt(Math.floor(amountFloat * 10 ** decimals0));
}
