module.exports = {
  apps: [
    {
      name: '9mm-rebalancer',
      script: 'dist/index.js',
      cwd: __dirname,
      node_args: '--enable-source-maps',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 10000,
      max_memory_restart: '512M',
      min_uptime: '10s',
      kill_timeout: 120000,
      env: {
        NODE_ENV: 'production',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: 'logs/pm2-error.log',
      out_file: 'logs/pm2-out.log',
      merge_logs: true,
      log_type: 'json',
    },
    {
      name: '9mm-dashboard',
      script: 'dist/server/index.js',
      cwd: __dirname,
      node_args: '--enable-source-maps',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 10000,
      max_memory_restart: '256M',
      min_uptime: '10s',
      kill_timeout: 5000,
      env: {
        NODE_ENV: 'production',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: 'logs/dashboard-error.log',
      out_file: 'logs/dashboard-out.log',
      merge_logs: true,
      log_type: 'json',
    },
    {
      name: '9mm-analytics-pruner',
      script: './scripts/prune-analytics.cjs',
      cwd: __dirname,
      instances: 1,
      autorestart: false,
      cron_restart: '0 0 * * 0', // Run once a week (Sunday at midnight)
      watch: false,
      env: {
        NODE_ENV: 'production',
      },
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      error_file: 'logs/pruner-error.log',
      out_file: 'logs/pruner-out.log',
    },
  ],
};
